import math

import numpy as np

from .triangular_filter import TriangularFilter
from .utils._gaussian_grid import reduced_gaussian_grid, spherical_triangulation

_LAT_NAMES = ("latitude", "lat", "latitudes")
_LON_NAMES = ("longitude", "lon", "longitudes")

#: Appended when both coordinates are 1-D but of different lengths: that is
#: the shape of a regular lat/lon grid's axes, not of a point list.
_REGULAR_GRID_HINT = (
    "; 1-D coordinates of different lengths usually describe a regular "
    "latitude/longitude grid -- use LatLonFilter for those"
)


def _find_coordinates(data):
    """Return (lat, lon) as 1-D float arrays from an xarray Dataset/DataArray."""
    # One merged namespace, so a pair split between a coordinate and a data
    # variable is still found. Coordinates win a name clash.
    available = dict(getattr(data, "data_vars", {}))
    available.update(getattr(data, "coords", {}))
    for lat_name, lon_name in zip(_LAT_NAMES, _LON_NAMES):
        if lat_name in available and lon_name in available:
            lat = np.asarray(available[lat_name].values, dtype=float)
            lon = np.asarray(available[lon_name].values, dtype=float)
            if lat.ndim != 1 or lon.ndim != 1:
                message = (
                    f"'{lat_name}' is {lat.ndim}-D and '{lon_name}' is "
                    f"{lon.ndim}-D, but a reduced Gaussian grid stores one "
                    "latitude and one longitude per point (1-D, along the "
                    "'values' dimension)."
                )
                if max(lat.ndim, lon.ndim) > 1:
                    message += (
                        " Multi-dimensional coordinates describe a regular "
                        "grid: use LatLonFilter for those."
                    )
                else:
                    message += (
                        " A 0-D coordinate is a single scalar, not a grid:"
                        " pass the full coordinate arrays to"
                        " prepare_from_points() instead."
                    )
                raise ValueError(message)
            if lat.shape != lon.shape:
                raise ValueError(
                    f"'{lat_name}' has {lat.size} values and '{lon_name}' has "
                    f"{lon.size}, but a reduced Gaussian grid stores one "
                    "latitude and one longitude per point"
                    + _REGULAR_GRID_HINT + "."
                )
            return lat, lon
    raise ValueError(
        "Could not find 1-D latitude/longitude coordinates; tried the name "
        f"pairs {list(zip(_LAT_NAMES, _LON_NAMES))} among coordinates "
        f"{list(getattr(data, 'coords', {}))} and data variables "
        f"{list(getattr(data, 'data_vars', {}))}. Pass the arrays to "
        "prepare_from_points() instead."
    )


class ReducedGaussianFilter(TriangularFilter):
    """
    Filter for data on ECMWF reduced Gaussian grids -- classical ``N`` grids
    such as N320 (native ERA5, AIFS input) and octahedral ``O`` grids such as
    O96 (Anemoi ERA5, AIFS training) -- or on any other set of points that
    covers the whole sphere.

    The grid points are Delaunay-triangulated on the sphere and filtered as
    the nodes of that mesh with the nodal operator of
    :class:`TriangularFilter`, using spherical tangent-plane triangle geometry
    (``meshtype='s'``) that stays well-behaved at the poles and across the
    date line. Data is a 1-D array in the grid's storage order -- rows north
    to south, each row west to east from 0 degrees longitude -- which is the
    ``values`` dimension of a GRIB message read with cfgrib and the layout of
    the public ERA5 zarr stores. Every capability of
    :class:`TriangularFilter` (velocity filtering, spectra, caching with
    :meth:`save_to_file`, backends, preconditioners) is inherited; element
    (triangle-centre) filtering is not available because the data is nodal by
    construction.

    Notes
    -----
    The triangulation is the convex hull of the points' unit vectors. Between
    two adjacent rows with the same number of points the quadrilaterals are
    planar and the choice of diagonal is arbitrary; coordinates of the same
    grid taken from two sources (e.g. generated by :func:`reduced_gaussian_grid`
    and read from a GRIB file) can therefore yield triangulations that differ
    in those diagonals. Both are valid meshes whose filters agree to
    discretisation accuracy; cache the filter (:meth:`save_to_file`) if
    bit-for-bit reproducibility across sessions matters.
    """

    def prepare_from_grid(self, grid: str, mask: np.ndarray | None = None, full: bool = False):
        """
        Configure the filter for a named ECMWF reduced Gaussian grid.

        Parameters
        ----------
        grid : str
            ``'O<N>'`` (octahedral, e.g. ``'O96'``) or ``'N<N>'`` (classical,
            e.g. ``'N320'``); case-insensitive. Octahedral grids exist for
            any ``N``; the classical ones are the 16 grids ecCodes ships
            definitions for (N32 to N2000, see
            :func:`implicit_filter.reduced_gaussian_grid`).
        mask : np.ndarray, optional
            Boolean array with one entry per grid point, ``True`` where the
            data is valid (e.g. ocean for SST). Points marked ``False`` are
            excluded from the operator and returned unchanged by
            :meth:`compute`; fill them with a neutral value (0) before
            filtering. Default: every point is valid.
        full : bool, optional
            Include the metric terms in the operator (default: False).
        """
        lat, lon = reduced_gaussian_grid(grid)
        self.prepare_from_points(lat, lon, mask=mask, full=full)

    def prepare_from_points(self, lat, lon, mask: np.ndarray | None = None,
                            full: bool = False, check_coverage: bool = True):
        """
        Configure the filter for an arbitrary set of points covering the
        sphere.

        Parameters
        ----------
        lat, lon : array_like
            1-D coordinates in degrees, one entry per data point, in the
            order of the data arrays that will be filtered. Any longitude
            convention (``[0, 360)`` or ``[-180, 180)``).
        mask : np.ndarray, optional
            Boolean array of the same shape, ``True`` where the data is
            valid. See :meth:`prepare_from_grid`.
        full : bool, optional
            Include the metric terms in the operator (default: False).
        check_coverage : bool, optional
            Set to False to skip the heuristic hole check of
            :func:`implicit_filter.spherical_triangulation` for point sets it
            wrongly rejects (e.g. a dense polar ring); the exact shape,
            coverage and duplicate checks always run.

        Raises
        ------
        ValueError
            If the coordinates are not 1-D arrays of equal length, do not
            cover the sphere (regional data), contain duplicates, or the mask
            has a different shape or is a float array containing NaN/inf.
        """
        lat = np.asarray(lat, dtype=float)
        lon = np.asarray(lon, dtype=float)
        if lat.ndim != 1 or lat.shape != lon.shape:
            message = (
                f"lat and lon must be 1-D arrays of equal length, got shapes "
                f"{lat.shape} and {lon.shape}")
            if lat.ndim == 1 and lon.ndim == 1:
                message += _REGULAR_GRID_HINT
            raise ValueError(message)
        if mask is not None:
            mask = np.asarray(mask)
            # bool(nan) is True, so a float mask carrying NaN would silently
            # mark the invalid points valid -- exactly the opposite of intent.
            if mask.dtype.kind == "f" and not np.all(np.isfinite(mask)):
                raise ValueError(
                    "mask contains NaN/inf; pass a boolean mask, e.g. "
                    "~np.isnan(field)")
            mask = mask.astype(bool)
            if mask.shape != lat.shape:
                raise ValueError(
                    f"mask must have one entry per point, shape {lat.shape}, "
                    f"got {mask.shape}")
        tri = spherical_triangulation(lat, lon, check_coverage=check_coverage)
        # An element is valid only if all its nodes are; elements touching an
        # invalid point get zero area, which is the Neumann boundary of the
        # nodal operator.
        elem_mask = None if mask is None else np.all(mask[tri], axis=1)
        self.prepare(
            lat.size,
            len(tri),
            tri,
            lon,
            lat,
            meshtype="s",
            cartesian=False,
            cyclic_length=2.0 * math.pi,
            full=full,
            mask=elem_mask,
        )

    def prepare_from_data_array(self, data, mask: np.ndarray | None = None,
                                full: bool = False, check_coverage: bool = True):
        """
        Configure the filter from the coordinates stored with the data.

        Parameters
        ----------
        data : xr.Dataset | xr.DataArray
            Object carrying 1-D latitude/longitude coordinates (or data
            variables) named ``latitude``/``longitude``, ``lat``/``lon`` or
            ``latitudes``/``longitudes`` -- as produced by cfgrib for a GRIB
            message on a reduced Gaussian grid, or by the ERA5 zarr stores.
        mask, full
            See :meth:`prepare_from_points`.
        check_coverage : bool, optional
            Set to False to skip the heuristic hole check of
            :func:`implicit_filter.spherical_triangulation` for point sets it
            wrongly rejects (e.g. a dense polar ring); the exact shape,
            coverage and duplicate checks always run.

        Raises
        ------
        ValueError
            If no such coordinates exist, or they are multi-dimensional
            (a regular grid; use :class:`LatLonFilter`).
        """
        lat, lon = _find_coordinates(data)
        self.prepare_from_points(
            lat, lon, mask=mask, full=full, check_coverage=check_coverage)

    def prepare_from_file(self, file: str, mask: np.ndarray | None = None,
                          full: bool = False, check_coverage: bool = True, **open_kwargs):
        """
        Configure the filter from the coordinates in a data file.

        Parameters
        ----------
        file : str
            Path opened with ``xarray.open_dataset(file, **open_kwargs)``;
            pass ``engine="cfgrib"`` for GRIB files.
        mask, full
            See :meth:`prepare_from_points`.
        check_coverage : bool, optional
            Set to False to skip the heuristic hole check of
            :func:`implicit_filter.spherical_triangulation` for point sets it
            wrongly rejects (e.g. a dense polar ring); the exact shape,
            coverage and duplicate checks always run.
        **open_kwargs
            Forwarded to ``xarray.open_dataset``.
        """
        import xarray as xr

        with xr.open_dataset(file, **open_kwargs) as ds:
            self.prepare_from_data_array(
                ds, mask=mask, full=full, check_coverage=check_coverage)
